trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

jobs:
- job: BuildAndTest
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: UiPathInstaller@2
    inputs:
      version: 'latest'

  - task: UiPathTest@1
    inputs:
      robotLicense: '<Your-Robot-License-File-Path>'
      projectPath: '$(Build.SourcesDirectory)/YourUiPathProjectPath'

  - task: UiPathBuild@2
    inputs:
      projectPath: '$(Build.SourcesDirectory)/YourUiPathProjectPath'
      buildDirectory: '$(Build.ArtifactStagingDirectory)'